### ISSUE TITLE
Pokemon go模拟位置无效

### ISSUE THREAD

**Issue by lubeast** [j2rong/FakeLocation#13]
测试了下微信，模拟位置成功，但是Pokemon go不行，请问作者有试过吗？

**Comment by asdf3309** [comment]
我这边是可以的

**Comment by lubeast** [comment]
啊？请问手机位置精度你设置的哪一个？

2016年7月17日 下午1:26，"dim" <notifications@github.com>写道：

**Comment by asdf3309** [comment]
好像是 38.559413 ，-121.452278

**Comment by asdf3309** [comment]
不能开模拟，需要root和xposed，这个是方式对吧？

**Comment by j2rong** [comment]
www.coolapk.com/apk/com.rong.xposed.fakelocation

**Comment by lubeast** [comment]
我和我朋友的手机都试了，都不行，再研究研究吧~估计是哪里设置错了 😅
