### ISSUE TITLE
overlay vanishes after a few seconds in PokemonGo

### ISSUE THREAD

**Issue by bymoz089** [j2rong/FakeLocation#17]
the overlay joystick is vanishing after a few seconds when using FakeLocation with Pokemon Go.

Otherwise best app I have seen so far, because it enables to enter gps coordinates with keyboard.

I am using Cyanogenmod 13 without Playstore but with "microG" (version 0.2.4-3, it is a open source UnifiedNlp and GoogleServices replacement, https://microg.org/) (with microG selecting point on Map seems not possible so entering GPS coordinates with keyboard is essential)

**Comment by j2rong** [comment]
Can you provide the mocking settings and the logs if possible

**Comment by j2rong** [comment]
#21

**Comment by seoaqua** [comment]
hi j2rong 你好，能私下聊几句吗？我微信628552，或者邮件也行628552@qq.com，多谢多谢~
