### ISSUE TITLE
Location jumping back to real location

### ISSUE THREAD

**Issue by Salatkopfwerfer** [j2rong/FakeLocation#19]
Hey there,  is there a way to set the max speed moving with the dpad? At the moment the options are locked. 

By the way, i recognized the location sometimes changes to my real location for about a second when using floating view, then it changes back to the fake location. Is there a workarround for this issue?

**Comment by roylaprattep** [comment]
I have the same issue with or without dpad. Always trying to go to my real location than return back to fake one, constantly, that's annoying when playing and get me banned sometimes cause of that.

**Comment by Salatkopfwerfer** [comment]
So it's not just me. I tried to disable GPS, but then it's Messing gps

**Comment by Salatkopfwerfer** [comment]
Whoops, wrong Button. 
So, again. Disabling GPS doesn't work. I have Set GPS mode to "only GPS", still getting this issue. I'm using galaxy Note 3 / Android 4.4.2

**Comment by roylaprattep** [comment]
No, you're not alone. That's very annoying. Sometimes it's doing this every 5 seconds...

**Comment by Salatkopfwerfer** [comment]
I've got another Problem, maybe you can confirm that too. Sometimes the Google App which has to be used for GPS mocking crashes. This happens randomly when using pad

**Comment by Salatkopfwerfer** [comment]
Sorry for closing / opening. Just flashed my device, i have to get used to it again

**Comment by j2rong** [comment]
I think that jumping back to the real location may be caused by the app calling `FusedLocationApi.getLastLocation()`, this function's mocking settings is working if you set to the app itself not `com.google.android.gms`

**Comment by roylaprattep** [comment]
What do you mean?!

**Comment by roylaprattep** [comment]
Is there a way to fix it? Sorry if I misunderstand you.

**Comment by roylaprattep** [comment]
j2rong: Is there a way to solve the issue falling back to real location?

Thanks man.

**Comment by j2rong** [comment]
working on a temporary workaround, but what's really causing this is still being investigated.

**Comment by roylaprattep** [comment]
Sweet, thanks. Let us know when it's done bro!

**Comment by j2rong** [comment]
I think it's fixed, feel free to reopen if there is any problem.

**Comment by roylaprattep** [comment]
There is no upgrade?

**Comment by roylaprattep** [comment]
0.8.404.813 only version available in Xposed Installer.

**Comment by roylaprattep** [comment]
Latest version available*

**Comment by roylaprattep** [comment]
Sorry! It's there now! Thanks man!

**Comment by roylaprattep** [comment]
Jumping back again... Issue not solve on LG G4 LG-H812.

Thanks.

**Comment by roylaprattep** [comment]
Hope you can find the issue...

**Comment by j2rong** [comment]
try turning off gps and what's your settings?

**Comment by roylaprattep** [comment]
GPS only in Location settings. Mock Mock Location installed + your FakeLocation app. That's it.

**Comment by roylaprattep** [comment]
If GPS turned off, Pokemon Go give me error "GPS signal not found" and I'm unable to play.

Thanks man.

**Comment by roylaprattep** [comment]
Oh, and, Mock location not on in developer's option since I am using Mock Mock Location, it doesn't allow me to tick option on.

**Comment by j2rong** [comment]
Try clear your settings in "com.google.android.gms" and set it in Pokemon (also connect with it)
If it still doesn't work, turn on log switch in Settings and post it please. (XposedInstaller - Log)

PS: The module doesn't need mock location permission

**Comment by roylaprattep** [comment]
Where do I clear that? What't that application?

Ok, gonna deactivate Mock Mock Location.

**Comment by roylaprattep** [comment]
I mean I know how to clear cache/settings, but what is the application name of "com.google.android.gms" ?

**Comment by j2rong** [comment]
Which package do you set to mock Poke's location?

**Comment by roylaprattep** [comment]
The one that contains Google Services.

**Comment by j2rong** [comment]
@roylaprattep Set and connect to Poke's package instead

**Comment by roylaprattep** [comment]
I FakeLocation on the Pokemon Go app? If so, the app give me the error "Failed to detect location".

"Allow mock location" enabled in Developer's options.

**Comment by roylaprattep** [comment]
No more FakeLocation on "Google services" too.

**Comment by roylaprattep** [comment]
Well... Faking location on Pokemon Go instead, doesn't work. I guess I will have to live with the problem...

**Comment by j2rong** [comment]
Can you provide some logs?
Turn on in FakeLocation's Settings, and run the game, the logs can be found in XposedInstaller

**Comment by roylaprattep** [comment]
Did you received my log file via email? I sent it.

**Comment by roylaprattep** [comment]
Well, keep me in touch buddy!

**Comment by j2rong** [comment]
@roylaprattep email not received, you can post it here

**Comment by roylaprattep** [comment]
I do not see option to attach a file?

**Comment by roylaprattep** [comment]
Give me your email please so I can send you the complete log file.

**Comment by roylaprattep** [comment]
[error.txt](https://github.com/j2rong/FakeLocation/files/461585/error.txt)

**Comment by roylaprattep** [comment]
Got it!

**Comment by roylaprattep** [comment]
Maybe you will have to rename it to "error.log", this was it's default name, github gave me error, isn't supporting extension ".log".

**Comment by j2rong** [comment]
@roylaprattep It looks like you are mocking `com.google.android.gms` and `com.nianticlabs.pokemongo` at the same time?

**Comment by roylaprattep** [comment]
No Polemon Go isn't mocking, I only tried this one time to test if it can solve the problem.

**Comment by roylaprattep** [comment]
Found any solution?

**Comment by roylaprattep** [comment]
Hellooo?  Is there anyone...? 
Still have no solution?
Just tell us if you can't find s solution...

**Comment by j2rong** [comment]
Sorry for the late reply,
Can't find anything in the log, but I'm working on several problems may related to this in future releases, you may try it then

**Comment by roylaprattep** [comment]
Rooted devices can't play anymore and RootCloak have no effect... Can you do something about it?

**Comment by j2rong** [comment]
@roylaprattep 
You can search 'Magisk'
