### ISSUE TITLE
toggle overlay disappeared after few mins

### ISSUE THREAD

**Issue by aniosjunk** [j2rong/FakeLocation#21]
Hi 

The fake gps work great except for the toggle overlay only work for a fees mins and sudden disappeared cannot enable again in pokemon go.

I'm using cynogenmod 13 on galaxy s3 international. Got the latest fake location installed. All setting are the same as my nexus 7 2013 cynogenmod 13 which don't have any issues with the toggle overlay joystick.

Do you have any ideas how to fix this. I also tested on galaxy s2. Overlay always disappeared in a few second.

**Comment by j2rong** [comment]
The overlay is running in the service `com.rong.xposed.fakelocation.service.f.FxService`, I think maybe it's because of low memory and android system kill the service/remove the overlay view.  You can use a system tool app to check whether the service is running when the overlay disappears

**Comment by aniosjunk** [comment]
Yeah I also think android system kill the service when memory are low.

Do you know any app can stop the system to kill fake location services?

Thanks

For the help.

**Comment by j2rong** [comment]
I'll make the service foreground to avoid being killed by system in next release. It should work in most case.
