### ISSUE TITLE
乐视手机微信双开，小号微信闪退

### ISSUE THREAD

**Issue by earthGavinLee** [j2rong/FakeLocation#23]
单独一个微信，正常。双开后，主微信正常，微信小号闪退。

**Comment by j2rong** [comment]
微信tinker的问题，找到双开对应的data目录，删除tinker目录中的内容，权限设为0，重启手机。
参考下列网页中的评论
http://www.coolapk.com/apk/com.tencent.mm
http://www.coolapk.com/apk/com.fkzhang.wechatunrecalled
