### ISSUE TITLE
xposed安装起来很多手机兼容性不是很好，不知可否换成动态注入的方式

### ISSUE THREAD

**Issue by 3412566455** [j2rong/FakeLocation#24]
xposed安装起来很多手机兼容性不是很好，不知可否换成动态注入的方式

**Comment by j2rong** [comment]
动态注入也不见得兼容性更好吧

**Comment by 3412566455** [comment]
我觉得像天下游那样的定位做进程注入是不用安装xpose的，因为5.1的系统要想安装xposed要刷recovery，而进程注入会好很多
