### ISSUE TITLE
微信闪退

### ISSUE THREAD

**Issue by smilingsun** [j2rong/FakeLocation#26]
手机型号：红米 Note 3 全网通高配版
系统：CM 13.0-20160820-SNAPSHOT-ZNH5YAO0J4-kenzo
Wechat： 6.3.25
Xposed: version 86
Fake Location: 0.9.486.1041

开启该模块，微信就闪退，关闭就好了，求解决。

**Comment by j2rong** [comment]
按照`设置`-`微信兼容`所述进行操作。如仍闪退，点击该项开启兼容模式。

**Comment by smilingsun** [comment]
It works, thanks!
