### ISSUE TITLE
益动GPS无法使用自动移动

### ISSUE THREAD

**Issue by aviraxp** [j2rong/FakeLocation#28]
com.edooon.gps 3.0.1
同时开启GPS和基站模拟
系统设置已开启高精确度

**Comment by aviraxp** [comment]
[xposed_error_20161005_130746.txt](https://github.com/j2rong/FakeLocation/files/510075/xposed_error_20161005_130746.txt)

**Comment by j2rong** [comment]
正在写新功能，完成后会看看。
