### ISSUE TITLE
Support for android 5.1.1/添加android5.1.1支持

### ISSUE THREAD

**Issue by TiekHan** [j2rong/FakeLocation#3]
请添加支持给安卓5。1。1.我可以帮你测试。

**Comment by j2rong** [comment]
The module supports up to Android M.
I'm not sure what you're talking about, maybe you don't have Xposed installed?

**Comment by TiekHan** [comment]
I have xposed module installed.But the fake location dint work on my samsung galaxy note 4 N910C android 5.1.1

**Comment by j2rong** [comment]
Can you post the log in Xposed Installer

**Comment by TiekHan** [comment]
05-19 19:21:33.513 I/Xposed  (27758): -----------------
05-19 19:21:33.513 I/Xposed  (27758): Starting Xposed version 81.0 (custom build by wanam / 20160411), compiled for SDK 22
05-19 19:21:33.513 I/Xposed  (27758): Device: SM-N910C (samsung), Android version 5.1.1 (SDK 22)
05-19 19:21:33.513 I/Xposed  (27758): ROM: LMY47X.N910CXXS2CPB3
05-19 19:21:33.513 I/Xposed  (27758): Build fingerprint: samsung/treltexx/trelte:5.1.1/LMY47X/N910CXXS2CPB3:user/release-keys
05-19 19:21:33.513 I/Xposed  (27758): Platform: armeabi-v7a, 32-bit binary, system server: yes
05-19 19:21:33.513 I/Xposed  (27758): SELinux enabled: yes, enforcing: yes
05-19 19:21:33.528 I/Xposed  (27758): -----------------
05-19 19:21:33.528 I/Xposed  (27758): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-19 19:21:34.228 I/Xposed  (27758): Detected ART runtime
05-19 19:21:34.263 I/Xposed  (27758): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-19 19:21:34.658 I/Xposed  (27758): Loading modules from /data/app/com.fkzhang.wechatunrecalled-1/base.apk
05-19 19:21:34.813 I/Xposed  (27758):   Loading class com.fkzhang.wechatunrecalled.XposedInit
05-19 19:21:34.823 I/Xposed  (27758): Loading modules from /data/app/com.xingress.xglyph-1/base.apk
05-19 19:21:34.838 I/Xposed  (27758):   Loading class com.xingress.xglyph.Xglyph
05-19 19:21:34.843 I/Xposed  (27758): Loading modules from /data/app/com.wuxianlin.luckymoney-1/base.apk
05-19 19:21:34.893 I/Xposed  (27758):   Loading class com.wuxianlin.luckymoney.LuckyMoney
05-19 19:21:34.898 I/Xposed  (27758): Loading modules from /data/app/com.fkzhang.wechatcontactsmanager-2/base.apk
05-19 19:21:34.978 I/Xposed  (27758):   Loading class com.fkzhang.wechatcontactsmanager.XposedInit
05-19 19:21:35.003 I/Xposed  (27758): Loading modules from /data/app/com.wuxianlin.randomgame-1/base.apk
05-19 19:21:35.063 I/Xposed  (27758):   Loading class com.wuxianlin.randomgame.RandomGame
05-19 19:21:35.078 I/Xposed  (27758): Loading modules from /data/app/ma.wanam.xposedlollipop-1/base.apk
05-19 19:21:35.113 I/Xposed  (27758):   Loading class ma.wanam.xposedlollipop.Xposed
05-19 19:21:35.123 I/Xposed  (27758): Loading modules from /data/app/com.rong.xposed.fakelocation-1/base.apk
05-19 19:21:35.193 I/Xposed  (27758):   Loading class com.rong.xposed.fakelocation.XFakeLocation
05-19 19:21:35.203 I/Xposed  (27758): [initZygote] log status = false
05-19 19:21:36.638 E/Xposed  (28152): java.lang.NoSuchMethodError: com.android.server.display.DisplayPowerController#animateScreenStateChange(int,boolean)#exact
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:272)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:144)
05-19 19:21:36.638 E/Xposed  (28152): 	at ma.wanam.xposedlollipop.XElectronBeam.initZygote(Unknown Source)
05-19 19:21:36.638 E/Xposed  (28152): 	at ma.wanam.xposedlollipop.Xposed.handleLoadPackage(Unknown Source)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:246)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
05-19 19:21:36.638 E/Xposed  (28152): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
05-19 19:21:36.638 E/Xposed  (28152): 	at com.android.server.SystemServer.run(SystemServer.java:452)
05-19 19:21:36.638 E/Xposed  (28152): 	at com.android.server.SystemServer.main(SystemServer.java:353)
05-19 19:21:36.638 E/Xposed  (28152): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 19:21:36.638 E/Xposed  (28152): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-19 19:21:36.638 E/Xposed  (28152): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
05-19 19:21:36.638 E/Xposed  (28152): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
05-19 19:21:36.638 E/Xposed  (28152): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
05-19 19:21:48.238 I/Xposed  (28803): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:21:49.138 I/Xposed  (28803): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:21:55.488 I/Xposed  (28803): enabling autoreply
05-19 19:21:55.493 I/Xposed  (28803): switch: false
05-19 19:21:55.493 I/Xposed  (28803): exclude: 
05-19 19:21:55.568 I/Xposed  (28803): delay: 0
05-19 19:21:55.568 I/Xposed  (28803): active users:130
05-19 19:22:03.012 I/Xposed  (30699): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:22:03.172 I/Xposed  (30699): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:22:36.982 I/Xposed  ( 3382): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:22:37.452 I/Xposed  ( 3382): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:22:41.702 I/Xposed  ( 3382): enabling autoreply
05-19 19:22:41.722 I/Xposed  ( 3382): switch: false
05-19 19:22:41.722 I/Xposed  ( 3382): exclude: 
05-19 19:22:41.732 I/Xposed  ( 3382): delay: 0
05-19 19:22:41.732 I/Xposed  ( 3382): active users:130
05-19 19:22:43.432 I/Xposed  ( 4005): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:22:43.612 I/Xposed  ( 4005): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:23:01.992 I/Xposed  ( 5590): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:23:02.282 I/Xposed  ( 5590): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:23:04.497 I/Xposed  ( 5590): enabling autoreply
05-19 19:23:04.507 I/Xposed  ( 5590): switch: false
05-19 19:23:04.507 I/Xposed  ( 5590): exclude: 
05-19 19:23:04.517 I/Xposed  ( 5590): delay: 0
05-19 19:23:04.517 I/Xposed  ( 5590): active users:130
05-19 19:23:18.552 I/Xposed  ( 6676): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:23:18.677 I/Xposed  ( 6676): WechatContactsManager (1.5.0)  Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-19 19:29:43.317 E/Xposed  (10413): java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:371)
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:384)
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1124)
05-19 19:29:43.317 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.e.b(Unknown Source)
05-19 19:29:43.317 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.u.afterHookedMethod(Unknown Source)
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.location.LocationManager.getGpsStatus(<Xposed>)
05-19 19:29:43.317 E/Xposed  (10413): 	at o.apu$7.onGpsStatusChanged(SourceFile:335)
05-19 19:29:43.317 E/Xposed  (10413): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 19:29:43.317 E/Xposed  (10413): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1124)
05-19 19:29:43.317 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.b.b(Unknown Source)
05-19 19:29:43.317 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.u.afterHookedMethod(Unknown Source)
05-19 19:29:43.317 E/Xposed  (10413): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.location.LocationManager.addGpsStatusListener(<Xposed>)
05-19 19:29:43.317 E/Xposed  (10413): 	at o.apu.ˏ(SourceFile:9858)
05-19 19:29:43.317 E/Xposed  (10413): 	at o.apu$9.run(SourceFile:489)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.os.Handler.handleCallback(Handler.java:739)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.os.Looper.loop(Looper.java:145)
05-19 19:29:43.317 E/Xposed  (10413): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-19 19:29:43.322 E/Xposed  (10413): java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:333)
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:384)
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1124)
05-19 19:29:43.322 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.e.b(Unknown Source)
05-19 19:29:43.322 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.u.afterHookedMethod(Unknown Source)
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.location.LocationManager.getGpsStatus(<Xposed>)
05-19 19:29:43.322 E/Xposed  (10413): 	at o.apu$7.onGpsStatusChanged(SourceFile:335)
05-19 19:29:43.322 E/Xposed  (10413): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 19:29:43.322 E/Xposed  (10413): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1124)
05-19 19:29:43.322 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.b.b(Unknown Source)
05-19 19:29:43.322 E/Xposed  (10413): 	at com.rong.xposed.fakelocation.x.u.afterHookedMethod(Unknown Source)
05-19 19:29:43.322 E/Xposed  (10413): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.location.LocationManager.addGpsStatusListener(<Xposed>)
05-19 19:29:43.322 E/Xposed  (10413): 	at o.apu.ˏ(SourceFile:9858)
05-19 19:29:43.322 E/Xposed  (10413): 	at o.apu$9.run(SourceFile:489)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.os.Handler.handleCallback(Handler.java:739)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.os.Looper.loop(Looper.java:145)
05-19 19:29:43.322 E/Xposed  (10413): 	at android.os.HandlerThread.run(HandlerThread.java:61)



After i install ur last update it works now.
