### ISSUE TITLE
通过地图选取坐标 发现以下情况

### ISSUE THREAD

**Issue by tomgogogo** [j2rong/FakeLocation#40]
今天从1.0升级到了最新版 但是出现以下情况：
1。通过高德地图选取坐标 当zoomin放大到20km比例时不在显示地图详细内容 只有白色一片 点击屏幕白点提示这点坐标
2。通过谷歌地图选取坐标时 无论多大比例缩放 都不显示地图详细内容 只有白色一片 但是点击屏幕白点提示这点坐标
本人手机是小米NOTE 4.4.4版本android，两台小米上都试过 都是一样的问题 在小米4上也试过了 也是同样的问题。。。心碎了

但是退回到1.0版本 就又好了、、、、
总结就是地图选取坐标无法看到地图具体的内容 求大神指点 感激不尽

**Comment by tomgogogo** [comment]
最新的1.2和1.1版本都有这样问题  但是1.0版本没有这样的问题 请教大神 应该不是我本地浏览器的问题！

**Comment by j2rong** [comment]
不确定是什么问题，
- 1.1更新了高德地图SDK，也可能于此有关。
- Google地图这几版没有修改过，没有显示可能是需要科学上网

**Comment by tomgogogo** [comment]
感谢回复
1.恳求以后版本解决高德sdk问题 不然我只能用1.0版本
2.我在国外 没有科学上网问题 哈哈

感谢 盼回复

**Comment by j2rong** [comment]
高德国外地图只有部分国家有详细内容。
