### ISSUE TITLE
App crash upon loading

### ISSUE THREAD

**Issue by roshanravan** [j2rong/FakeLocation#6]
App crash on startup, here is my log
[Crash_160713_0146.log.zip](https://github.com/j2rong/FakeLocation/files/360284/Crash_160713_0146.log.zip)
Any idea or solution??

**Comment by j2rong** [comment]
Try v0.7.306. I think it's fixed, feel free to reopen if there is still problems

**Comment by roshanravan** [comment]
Now after the update Works just fine again. Thank you
