### ISSUE TITLE
地图选择坐标的建议

### ISSUE THREAD

**Issue by hylin** [j2rong/FakeLocation#7]
1.点击选择后打开的地图，建议定位到前面文本框里的坐标，而不是每次都默认到故宫
2.希望可以记住选择的地图类型，现在每次都是默认到高德
TKS

**Comment by j2rong** [comment]
1、地图选择地点后点击右下角按钮才会保存到最近列表中，第二次打开会使用最近的地点。
2、地图类型目前由系统区域设置确定，国内默认高德。

**Comment by gameclamp** [comment]
@j2rong 我确定我有点右下角的√，但是重启手机之后，还是回到故宫了。

**Comment by j2rong** [comment]
请查看最新版
